"""Reporter — Clinical PDF report generation for SCID-5-CV sessions.

Generates a structured report from a completed session:
  1. Session header + disclaimer
  2. Module summary table (questions answered, threshold items per module)
  3. Detailed findings per module (score, transcript, AI rationale)
  4. Unresolved items requiring clinician review
"""

from datetime import datetime
from pathlib import Path

from fpdf import FPDF


def _safe(text: str) -> str:
    """Replace characters outside Latin-1 so fpdf2 built-in fonts don't choke."""
    if not text:
        return ""
    replacements = {
        "\u00e4": "ae", "\u00f6": "oe", "\u00fc": "ue",
        "\u00c4": "Ae", "\u00d6": "Oe", "\u00dc": "Ue",
        "\u00df": "ss",
        "\u2014": "--", "\u2013": "-",
        "\u201c": '"', "\u201d": '"',
        "\u2018": "'", "\u2019": "'",
        "\u2026": "...",
        "\u00b0": " degrees",
        "\u2192": "->", "\u2190": "<-", "\u2194": "<->",
        "\u00e9": "e", "\u00e8": "e", "\u00ea": "e",
        "\u00e0": "a", "\u00e2": "a",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    # Drop anything still outside Latin-1
    return text.encode("latin-1", errors="replace").decode("latin-1")


class _Report(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 9)
        self.cell(0, 7, "SCID-5-CV AI-Assisted Diagnostic Report", align="C",
                  new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def footer(self):
        self.set_y(-18)
        self.set_font("Helvetica", "I", 7)
        self.cell(0, 4,
                  "Generated by SCID-5-CV AI Pipeline -- not a substitute for clinical judgment",
                  align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 4, f"Page {self.page_no()}/{{nb}}", align="C")


def generate_pdf(session: dict, questions: dict, output_path: Path) -> Path:
    """Generate the clinical PDF report.

    Args:
        session: Completed session state dict.
        questions: Loaded questions.json data.
        output_path: Where to write the PDF.

    Returns:
        Path to the written PDF.
    """
    pdf = _Report()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=22)
    pdf.add_page()

    responses = session.get("interview_responses", {})
    summaries = session.get("module_summaries", {})
    lang = session.get("language", "en")

    # Build a flat question index for lookups
    q_index: dict[str, dict] = {}
    for module in questions.get("modules", []):
        for q in module["questions"]:
            q_index[q["id"]] = {**q, "module_id": module["id"],
                                 "module_name": module.get("name_en", module["id"])}

    # ------------------------------------------------------------------ #
    # Section 1: Title + session info
    # ------------------------------------------------------------------ #
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "SCID-5-CV Diagnostic Assessment", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Session ID : {session.get('session_id', 'N/A')}",
             new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Date       : {session.get('created_at', datetime.now().isoformat())[:10]}",
             new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Language   : {session.get('language', 'en').upper()}",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    pdf.set_font("Helvetica", "BI", 8)
    pdf.multi_cell(0, 4, _safe(
        "DISCLAIMER: This report is generated by an AI-assisted tool and is intended to support "
        "-- not replace -- clinical judgment. All findings must be reviewed and confirmed by a "
        "licensed clinician before any diagnostic conclusions are made."
    ))
    pdf.ln(5)

    # ------------------------------------------------------------------ #
    # Section 2: Module summary table
    # ------------------------------------------------------------------ #
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Module Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    col_w = [20, 90, 35, 35]
    pdf.set_font("Helvetica", "B", 9)
    for w, h in zip(col_w, ["Module", "Name", "Answered", "Threshold (+)"]):
        pdf.cell(w, 7, h, border=1, align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 9)
    for module in questions.get("modules", []):
        mid = module["id"]
        name = module.get("name_en", mid)
        s = summaries.get(mid, {})
        answered = s.get("questions_answered", 0)
        threshold = s.get("threshold_count", 0)
        pdf.cell(col_w[0], 6, mid, border=1, align="C")
        pdf.cell(col_w[1], 6, _safe(name[:55]), border=1)
        pdf.cell(col_w[2], 6, str(answered), border=1, align="C")
        pdf.cell(col_w[3], 6, str(threshold), border=1, align="C")
        pdf.ln()

    pdf.ln(6)

    # ------------------------------------------------------------------ #
    # Section 3: Detailed findings per module
    # ------------------------------------------------------------------ #
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Detailed Findings", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    score_labels = {"+": "Present (+)", "-": "Absent (-)", "?": "Inadequate Info (?)"}

    for module in questions.get("modules", []):
        mid = module["id"]
        module_qs = [q for q in module["questions"] if q["id"] in responses]
        if not module_qs:
            continue

        # Module heading
        if pdf.get_y() > 240:
            pdf.add_page()
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, _safe(f"Module {mid}: {module.get('name_en', mid)}"),
                 new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        for q in module_qs:
            qid = q["id"]
            result = responses[qid]
            score = result.get("score", "?")

            if score == "skip":
                continue

            if pdf.get_y() > 245:
                pdf.add_page()

            lm = pdf.l_margin

            # Criterion label + score
            label = _safe(q.get("criterion_label", qid))
            score_str = score_labels.get(score, score)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_x(lm)
            pdf.cell(0, 6, _safe(f"[{qid}] {label}  --  {score_str}"), new_x="LMARGIN", new_y="NEXT")

            # Confidence + unresolved flag
            confidence = result.get("confidence", "")
            unresolved = result.get("unresolved", False)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_x(lm)
            status_line = f"Confidence: {confidence}"
            if unresolved:
                status_line += "  [UNRESOLVED — needs clinician review]"
            pdf.cell(0, 5, _safe(status_line), new_x="LMARGIN", new_y="NEXT")

            # Transcript
            transcript = result.get("transcript", "").strip()
            if transcript:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_x(lm + 5)
                pdf.multi_cell(0, 4, _safe(f'Patient: "{transcript[:600]}"'),
                               new_x="LMARGIN", new_y="NEXT")

            # Follow-up exchanges (multi-round clarification)
            for i, ex in enumerate(result.get("exchanges") or [], 1):
                pdf.set_font("Helvetica", "BI", 8)
                pdf.set_x(lm + 5)
                pdf.multi_cell(0, 4, _safe(f"Follow-up {i}: {ex.get('question', '')}"),
                               new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_x(lm + 5)
                pdf.multi_cell(0, 4, _safe(f'Answer {i}: "{ex.get("answer", "")[:400]}"'),
                               new_x="LMARGIN", new_y="NEXT")

            # AI rationale
            rationale = result.get("reasoning") or result.get("rationale", "")
            if rationale:
                pdf.set_font("Helvetica", "", 8)
                pdf.set_x(lm + 5)
                pdf.multi_cell(0, 4, _safe(f"AI Rationale: {rationale[:500]}"),
                               new_x="LMARGIN", new_y="NEXT")

            pdf.ln(2)

        pdf.ln(3)

    # ------------------------------------------------------------------ #
    # Section 4: Unresolved items
    # ------------------------------------------------------------------ #
    unresolved = [(qid, r) for qid, r in responses.items() if r.get("unresolved")]
    if unresolved:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Unresolved Items Requiring Clinician Review",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        lm = pdf.l_margin
        for qid, result in unresolved:
            q_data = q_index.get(qid, {})
            label = _safe(q_data.get("criterion_label", qid))
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_x(lm)
            pdf.cell(0, 6, f"[{qid}] {label}", new_x="LMARGIN", new_y="NEXT")

            pdf.set_font("Helvetica", "", 8)
            pdf.set_x(lm)
            rationale = result.get("reasoning") or result.get("rationale", "")
            pdf.multi_cell(0, 4, _safe(f"Reason: {rationale[:300]}"),
                           new_x="LMARGIN", new_y="NEXT")

            clar_q = result.get("clarifying_question")
            if clar_q:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_x(lm)
                pdf.multi_cell(0, 4, _safe(f"Suggested follow-up: {clar_q}"),
                               new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(output_path))
    return output_path
