"""Stage 4: Reporter — Clinical PDF report generation.

Generates a structured clinical PDF report from a completed session,
including summary table, detailed findings, and unresolved items.
"""

import json
from datetime import datetime
from pathlib import Path

from fpdf import FPDF

DATA_DIR = Path(__file__).resolve().parent.parent / "data"


class ClinicalReport(FPDF):
    """Custom PDF class for SCID-5-PD clinical reports."""

    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 8, "SCID-5-PD AI-Assisted Diagnostic Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 7)
        self.cell(0, 5, "Generated by SCID-5 PD AI Wrapper -- not a substitute for clinical judgment", align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", align="C")


def _safe_text(text: str) -> str:
    """Replace problematic Unicode characters for fpdf2 with Latin-1 safe equivalents."""
    replacements = {
        "\u00e4": "ae", "\u00f6": "oe", "\u00fc": "ue",
        "\u00c4": "Ae", "\u00d6": "Oe", "\u00dc": "Ue",
        "\u00df": "ss",
        "\u2014": "--", "\u2013": "-",
        "\u201c": '"', "\u201d": '"',
        "\u2018": "'", "\u2019": "'",
        "\u2026": "...",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def generate_pdf(session: dict, questions: dict, output_path: Path) -> Path:
    """Generate a clinical PDF report from session data.

    Args:
        session: The session state dict.
        questions: The questions.json data.
        output_path: Where to save the PDF.

    Returns:
        Path to the generated PDF.
    """
    pdf = ClinicalReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    # --- Section 1: Header Info ---
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "SCID-5-PD Diagnostic Assessment", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Session ID: {session.get('session_id', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Date: {session.get('created_at', datetime.now().isoformat())[:10]}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Language: {session.get('language', 'de').upper()}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Disclaimer
    pdf.set_font("Helvetica", "BI", 9)
    pdf.multi_cell(0, 5, _safe_text(
        "DISCLAIMER: This report is generated by an AI-assisted tool and is intended "
        "to support — not replace — clinical judgment. All findings must be reviewed "
        "and confirmed by a licensed clinician before any diagnostic conclusions are made."
    ))
    pdf.ln(6)

    # --- Section 2: Summary Table ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Diagnostic Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Table header
    col_widths = [55, 20, 30, 25, 30, 30]
    headers = ["Disorder", "Cluster", "Criteria Met", "Threshold", "Diagnosis", "Status"]
    pdf.set_font("Helvetica", "B", 9)
    for i, h in enumerate(headers):
        pdf.cell(col_widths[i], 7, h, border=1, align="C")
    pdf.ln()

    # Table rows
    pdf.set_font("Helvetica", "", 9)
    disorder_verdicts = session.get("disorder_verdicts", {})
    exploration_results = session.get("exploration_results", {})

    for disorder_key, disorder_data in questions.get("disorders", {}).items():
        verdict = disorder_verdicts.get(disorder_key, {})
        name = disorder_data.get("name_en", disorder_key.title())
        cluster = disorder_data.get("cluster", "?")
        criteria_met = verdict.get("criteria_met", 0)
        threshold = disorder_data.get("threshold", "?")
        diagnosis = verdict.get("diagnosis", None)

        if diagnosis is True:
            diag_str = "YES"
        elif diagnosis is False:
            diag_str = "No"
        else:
            diag_str = "N/A"

        # Check if any criteria are unresolved
        has_unresolved = False
        for crit_id in disorder_data.get("criteria", {}):
            if crit_id in exploration_results and exploration_results[crit_id].get("unresolved"):
                has_unresolved = True
                break

        status = "Needs Review" if has_unresolved else ("Explored" if disorder_key in disorder_verdicts else "Not Explored")

        row = [_safe_text(name), cluster, str(criteria_met), str(threshold), diag_str, status]
        for i, val in enumerate(row):
            pdf.cell(col_widths[i], 7, val, border=1, align="C")
        pdf.ln()

    pdf.ln(6)

    # --- Section 3: Detailed Findings ---
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Detailed Findings", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    lang = session.get("language", "de")
    lang_suffix = f"_{lang}"

    for disorder_key, disorder_data in questions.get("disorders", {}).items():
        criteria = disorder_data.get("criteria", {})
        explored_criteria = {cid: exploration_results[cid] for cid in criteria if cid in exploration_results}

        if not explored_criteria:
            continue

        # Disorder heading
        pdf.set_font("Helvetica", "B", 11)
        name = disorder_data.get("name_en", disorder_key.title())
        pdf.cell(0, 7, _safe_text(f"{name} (Cluster {disorder_data.get('cluster', '?')})"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for crit_id, result in explored_criteria.items():
            crit_data = criteria.get(crit_id, {})
            lm = pdf.l_margin

            # Ensure enough space for a criterion block, otherwise start new page
            if pdf.get_y() > 240:
                pdf.add_page()

            # Criterion header
            pdf.set_font("Helvetica", "B", 9)
            desc = crit_data.get(f"description{lang_suffix}", crit_data.get("description_en", crit_id))
            score = result.get("score", "?")
            score_label = {"?": "Inadequate Info", 0: "Absent", 1: "Sub-threshold", 2: "Threshold"}.get(score, "?")
            pdf.set_x(lm)
            pdf.multi_cell(w=0, h=6, text=_safe_text(f"{crit_id}: {desc}"), new_x="LMARGIN", new_y="NEXT")

            pdf.set_font("Helvetica", "", 9)
            pdf.set_x(lm)
            pdf.cell(0, 6, f"Score: {score} ({score_label})  |  Confidence: {result.get('confidence', '?')}", new_x="LMARGIN", new_y="NEXT")

            if result.get("unresolved"):
                pdf.set_font("Helvetica", "BI", 9)
                pdf.set_x(lm)
                pdf.cell(0, 6, "[UNRESOLVED - Needs clinician review]", new_x="LMARGIN", new_y="NEXT")

            # Transcript
            transcript = result.get("transcript", "")
            if transcript:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_x(lm + 5)
                pdf.multi_cell(w=0, h=4, text=_safe_text(f'Patient: "{transcript[:500]}"'), new_x="LMARGIN", new_y="NEXT")

            # Rationale
            rationale = result.get("rationale", "")
            if rationale:
                pdf.set_font("Helvetica", "", 8)
                pdf.set_x(lm + 5)
                pdf.multi_cell(w=0, h=4, text=_safe_text(f"AI Rationale: {rationale[:500]}"), new_x="LMARGIN", new_y="NEXT")

            # Clarification transcript if present
            clarification = result.get("clarification_transcript")
            if clarification:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_x(lm + 5)
                pdf.multi_cell(w=0, h=4, text=_safe_text(f'Clarification: "{clarification[:500]}"'), new_x="LMARGIN", new_y="NEXT")

            pdf.ln(3)

    # --- Section 4: Unresolved Items ---
    unresolved_items = []
    for crit_id, result in exploration_results.items():
        if result.get("unresolved"):
            unresolved_items.append((crit_id, result))

    if unresolved_items:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Unresolved Items Requiring Clinician Review", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        lm = pdf.l_margin
        for crit_id, result in unresolved_items:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_x(lm)
            pdf.cell(0, 6, _safe_text(f"{crit_id}"), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.set_x(lm)
            score_text = _safe_text(
                f"Score: {result.get('score', '?')} | Confidence: {result.get('confidence', '?')}\n"
                f"Reason: {result.get('rationale', 'N/A')[:300]}"
            )
            pdf.multi_cell(w=0, h=5, text=score_text, new_x="LMARGIN", new_y="NEXT")
            clarifying = result.get("clarifying_question")
            if clarifying:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_x(lm)
                clar_text = _safe_text(f"Suggested question: {clarifying}")
                pdf.multi_cell(w=0, h=4, text=clar_text, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

    # Save
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(output_path))
    return output_path
